name: FreezeGUI
version: '${project.version}'
main: freezegui.freezegui.FreezeGUI
api-version: 1.16
description: This is a freeze command plugin that is perfect for any 1.16+ servers that want a good, reliable command to catch cheaters via Screenshare etc;
commands:
  freeze:
    description: Freezes a player
    permission: FreezeGUI.freeze
  unfreeze:
    description: UnFreezes a player
    permission: FreezeGUI.unfreeze